"""create contracts, renewal_history, documents tables

Revision ID: 1f6ef99dae17
Revises: 
Create Date: 2026-07-19 00:52:41.750482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6ef99dae17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRING', 'EXPIRED', 'RENEWED', name='contract_status'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_contract_id'), ['contract_id'], unique=False)

    op.create_table('renewal_history',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('previous_end_date', sa.Date(), nullable=False),
    sa.Column('new_end_date', sa.Date(), nullable=False),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renewal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renewal_history_contract_id'), ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renewal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renewal_history_contract_id'))

    op.drop_table('renewal_history')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_contract_id'))

    op.drop_table('documents')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_contracts_end_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_category'))

    op.drop_table('contracts')
    # ### end Alembic commands ###
